### ISSUE TITLE
bwdist

### ISSUE THREAD

**Issue by yakir12** [JuliaStats/Distance.jl#10]
[enhancement] It would be freaking awesome if you could add a bwdist function. A function that will take *an instance of a distance type* and *an n-dimensional array of Bool*. It will then return *an array with the same size as the input array where each cell has the distance to the closest true containing cell*.
In addition: it might be relevant in this respect to return memory-cheap types dependent on the distance metric. Since the returned distances in bwdist will be whole positive numbers for many of the distance metrics (e.g. SqEuclidean, Cityblock, Chebyshev, Hamming, etc), it might be cool to work in Uint8, 16, 32, 64, or 128 (dependent on the largest possible distance) just to save place without any loss of accuracy. I guess the easiest is to just add "cheap" versions of those types (e.g. CheapSqEuclidean) to the set of existing distance types.

Hope you find this easy and fun!

**Comment by IainNZ** [comment]
Looks like this is being dealt with in Images
