### ISSUE TITLE
Jensen–Shannon divergence for probability distributions (more than two distribution)

### ISSUE THREAD

**Issue by yulijia** [JuliaStats/Distance.jl#13]
Hi all, I want to use JSDistance function to calculate divergence of 10 probability distributions, however I found that the default JSDistanc function only can compare the divergence of two distributions. 
Could I add a [JSmetric function](https://github.com/yulijia/Distance.jl/blob/master/src/metrics.jl#L288-L308) for this package? 
The square root of the Jensen–Shannon divergence is a metric. In bioinformatics field, we often use it to test isoform abundance changes among multiple expreiments in RNA-Seq data.  

Here is the Jensen-Shannon divergence of *m* discrete probability distributions (<code>p^1, ...,p^m </code>): 
```
JSmetric(p^1,...,p^m)=H(\frac{p^1+...+p^m}{m})-\frac{\sum_{j=1}^{m} H(p^j)}{m} 
```
where <code>H()</code> is entropy.

**Comment by IainNZ** [comment]
Hi @yulijia , development on this package shifted to [Distances.jl](https://github.com/JuliaStats/Distances.jl), feel free to re-open there if this is still an issue.
