### ISSUE TITLE
ERROR in mahalanobis distance , waht is Q?

### ISSUE THREAD

**Issue by paulanalyst** [JuliaStats/Distance.jl#16]
mahalanobis(x, y, Q) 
x and y it's vectors
Q must be covariance ...

julia> Q=cov(x,y)
28.409813261664944

julia> mahalanobis(x, y, Q)
ERROR: no method mahalanobis(Array{Float64,1}, Array{Float64,1}, Float64)

julia>

**Comment by IainNZ** [comment]
Hi @paulanalyst , development on this package shifted to [Distances.jl](https://github.com/JuliaStats/Distances.jl), feel free to re-open there if this is still an issue.

**Comment by paulanalyst** [comment]
Steel not work

```
           _
```

   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3600 (2015-02-25 15:26 UTC)
 _/ |\__'_|_|_|__'_|  |  Commit f96c23c\* (20 days old master)
|__/                   |  x86_64-w64-mingw32

julia> pkg.update()
ERROR: UndefVarError: pkg not defined

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of Compat...
INFO: Updating cache of Docile...
INFO: Computing changes...
INFO: Upgrading Compat: v0.2.12 => v0.3.3
INFO: Upgrading Docile: v0.4.5 => v0.4.7

julia> x=rand(100)
100-element Array{Float64,1}:
 0.0333695
 0.882473
...
 0.975794
 0.30439

julia> y=rand(100)
100-element Array{Float64,1}:
 0.66611
 0.182463
...
 0.92105
 0.740463

julia> Q=cov(x,y)
-0.0023201822668934926

julia> using Distance
ERROR: ArgumentError: Distance not found in path
 in require at loading.jl:47

julia> Pkg.add("Distance")
INFO: Cloning cache of ArrayViews from git://github.com/JuliaLang/ArrayViews.jl.git
INFO: Cloning cache of Distance from git://github.com/JuliaStats/Distance.jl.git
INFO: Installing ArrayViews v0.4.10
INFO: Installing Distance v0.5.1
INFO: Package database updated

julia> using Distance
WARNING: The Distance.jl package is deprecated. Please use the new package Distances.jl instead.

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using Distance

Q=cov(x,y)
julia> Q
-0.0023201822668934926

julia> mahalanobis(x, y, Q)
ERROR: MethodError: `mahalanobis` has no method matching mahalanobis(::Array{Float64,1}, ::Array{Float64,1}, ::Flo
at64)
Closest candidates are:
  mahalanobis(::AbstractArray{T,1}, ::AbstractArray{T,1}, ::AbstractArray{T,2})

julia> mahalanobis(vec(x), vec(y), Q)
ERROR: MethodError: `mahalanobis` has no method matching mahalanobis(::Array{Float64,1}, ::Array{Float64,1}, ::Flo
at64)
Closest candidates are:
  mahalanobis(::AbstractArray{T,1}, ::AbstractArray{T,1}, ::AbstractArray{T,2})

**Comment by paulanalyst** [comment]
Distances under Julia 4:  
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3600 (2015-02-25 15:26 UTC)
 _/ |\__'_|_|_|__'_|  |  Commit f96c23c\* (20 days old master)
|__/                   |  x86_64-w64-mingw32

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of Compat...
INFO: Updating cache of Docile...
INFO: Computing changes...
INFO: Upgrading Compat: v0.2.12 => v0.3.3
INFO: Upgrading Docile: v0.4.5 => v0.4.7

julia> x=rand(100)
100-element Array{Float64,1}:
julia> y=rand(100)
100-element Array{Float64,1}:
julia> Q=cov(x,y)
-0.0023201822668934926

julia> Pkg.add("Distances")
INFO: Cloning cache of Distances from git://github.com/JuliaStats/Distances.jl.git
INFO: Installing Distances v0.2.0
INFO: Package database updated

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using Distances
Warning: using Distances.mahalanobis in module Main conflicts with an existing identifier.

julia> mahalanobis(vec(x), vec(y), Q)
ERROR: MethodError: `mahalanobis` has no method matching mahalanobis(::Array{Float64,1}, ::Array{Float64,1}, ::Flo
at64)
Closest candidates are:
  mahalanobis(::AbstractArray{T,1}, ::AbstractArray{T,1}, ::AbstractArray{T,2})

Paul
