### ISSUE TITLE
Loading distance package not responding.

### ISSUE THREAD

**Issue by mingot** [JuliaStats/Distance.jl#20]
In Julia Studio 0.4.4 on Mac OS X 10.9, I am unable to load the Distance package. When I run:

    julia> using Distance

Julia studio terminal do not respond, it never goes back to the prompt. I have tried to reinstall the package as well as to remove the `~/.julia` folder, but the problem persists.

    julia> Pkg.status()
    Required packages:
     - DataFrames                    0.4.3
     - Distance                      0.2.6
     - IJulia                        0.1.11             55b60c47 (dirty)
     - RDatasets                     0.1.1
    Additional packages:
      - BinDeps                       0.2.12
      - Blocks                        0.0.4
      - DataArrays                    0.0.3
      - GZip                          0.2.12
      - Homebrew                      0.0.6
      - JSON                          0.3.5
      - Nettle                        0.1.3
      - NumericExtensions             0.3.6
      - REPLCompletions               0.0.1
      - SortingAlgorithms             0.0.1
      - StatsBase                     0.3.8
      - URIParser                     0.0.2
      - ZMQ                           0.1.11

**Comment by IainNZ** [comment]
Hi @mingot , development on this package shifted to [Distances.jl](https://github.com/JuliaStats/Distances.jl), feel free to re-open there if this is still an issue.
