### ISSUE TITLE
Should the result type be of the same type as the input when possible?

### ISSUE THREAD

**Issue by lendle** [JuliaStats/Distance.jl#21]
Currently the result type is always `Float64` other than for the hamming metric and weighted (semi)metrics.  It would make sense in many cases for the result type to be of the same type as the inputs, for example `evaluate(dist::Euclidean,a::AbstractArray{Float32,1},b::AbstractArray{Float32,1})` could return a `Float32`. However, when `a` and `b` are vectors of `Int`s it would make sense to return a `Float64`.

What is the planned/intended behavior?

**Comment by IainNZ** [comment]
Hi @lendle, development on this package shifted to [Distances.jl](https://github.com/JuliaStats/Distances.jl), feel free to re-open there if this is still an issue.
