### ISSUE TITLE
Error submitting package with Distance.jl as dependency

### ISSUE THREAD

**Issue by cyrusmaher** [JuliaStats/Distance.jl#22]
I am trying to release a package that has Distance.jl and PyCall.jl as its only dependencies. I get the following errors when I use Pkg.publish(). Any thoughts on what I should do?

```
DataFrames v0.5.0 – no valid versions exist for package DataArrays
Distance v0.3.0 – no valid versions exist for package NumericExtensions
Distance v0.3.1 – no valid versions exist for package NumericExtensions
RDatasets v0.1.0 – no valid versions exist for package DataArrays
```

**Comment by IainNZ** [comment]
Hi @cyrusmaher , development on this package shifted to [Distances.jl](https://github.com/JuliaStats/Distances.jl), feel free to re-open there.
