### ISSUE TITLE
Adding support for Jaccard and Tanimoto distances?

### ISSUE THREAD

**Issue by tlnagy** [JuliaStats/Distance.jl#24]
It would be nice to add support for Jaccard distance and the [Rogers-Tanimoto dissimilarity](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.distance.rogerstanimoto.html) distance.

**Comment by IainNZ** [comment]
Hi @tlnagy, development on this package shifted to [Distances.jl](https://github.com/JuliaStats/Distances.jl), feel free to re-open there.
