### ISSUE TITLE
Please , remove Distance ffrom list of packages, 

### ISSUE THREAD

**Issue by paulanalyst** [JuliaStats/Distance.jl#26]
Hepy New Year;)
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.3 (2014-11-23 20:19 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using Distance
WARNING: The Distance package is deprecated. Please use a new package Distances instead.

Please , remove "Distance" ffrom list of packages
Paul

**Comment by lindahua** [comment]
There was discussion that. Packages should be *deprecated* but not removed.
